wallpaper {
	monitor = eDP-1
	path = /home/krystian/nixos-dotfiles/config/hypr/wpaper/nixos.jxl
	fit_mode = cover
}
wallpaper {
	monitor = HDMI-A-1
	path = /home/krystian/nixos-dotfiles/config/hypr/wpaper/nixos.jxl
	fit_mode = cover
}
